// <auto-generated/>
namespace Rauch.Core;

internal static class Usings
{
    public static readonly string[] Namespaces = new[]
    {
        "Rauch.Commands",
        "Rauch.Core",
        "Rauch.Core.Attributes",
        "static Rauch.Core.CommandUtils",
        "System",
        "System.Collections.Generic",
        "System.Diagnostics",
        "System.IO",
        "System.IO.Compression",
        "System.Linq",
        "System.Net.Http",
        "System.Text",
        "System.Threading",
        "System.Threading.Tasks"
    };
}
