param(
    [string]$UsingsFile,
    [string]$OutputFile
)

$lines = Get-Content $UsingsFile | Where-Object {
    $trimmed = $_.Trim()
    $trimmed.StartsWith("global using ")
}

$usings = $lines | ForEach-Object {
    $cleaned = $_.Trim().Replace("global using ", "").Replace(";", "")
    "        `"$cleaned`""
}

$content = @"
// <auto-generated/>
namespace Rauch.Core;

internal static class Usings
{
    public static readonly string[] Namespaces = new[]
    {
$($usings -join ",`n")
    };
}
"@

Set-Content -Path $OutputFile -Value $content -Encoding UTF8
